<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vivobook-asuslaptop-x512flc-x512fl" failures="1" tests="9" name="Error.Console_log.Cellannotation_consolelog" time="113.207" errors="0" timestamp="2024-02-13T17:31:18 IST" skipped="0">
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="login" time="11.740"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="series_set" time="15.946"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="cellannotation" time="2.442">
    <failure message="SEVERE logs were found in the console. expected [0] but found [9]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: SEVERE logs were found in the console. expected [0] but found [9]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at Error.Console_log.Cellannotation_consolelog.checkConsoleLog(Cellannotation_consolelog.java:326)
at Error.Console_log.Cellannotation_consolelog.cellannotation(Cellannotation_consolelog.java:185)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- cellannotation -->
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="Tileloading" time="7.048"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="centroidDetection" time="15.987"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="celldetection" time="16.040"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="Rabies" time="16.083"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="Annotation" time="11.938"/>
  <testcase classname="Error.Console_log.Cellannotation_consolelog" name="save" time="15.983"/>
</testsuite> <!-- Error.Console_log.Cellannotation_consolelog -->
